FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend /app/backend

RUN python -m pip install --upgrade pip \
    && python -m pip install ./backend

EXPOSE 8000

CMD ["uvicorn", "backend.control_main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
